apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: vs-blue
  labels: { app: ai-service, color: blue }
spec:
  type: ClusterIP
  selector: { app: ai-service, color: blue }
  ports:
    - { name: http, port: 8083, targetPort: 8083, protocol: TCP }
---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
  namespace: vs-green
  labels: { app: ai-service, color: green }
spec:
  type: ClusterIP
  selector: { app: ai-service, color: green }
  ports:
    - { name: http, port: 8083, targetPort: 8083, protocol: TCP }
