apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: vs-blue
  labels: { app: auth-service, color: blue }
spec:
  type: ClusterIP
  selector: { app: auth-service, color: blue }
  ports:
    - { name: http, port: 8082, targetPort: 8082, protocol: TCP }
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: vs-green
  labels: { app: auth-service, color: green }
spec:
  type: ClusterIP
  selector: { app: auth-service, color: green }
  ports:
    - { name: http, port: 8082, targetPort: 8082, protocol: TCP }
