apiVersion: v1
kind: Service
metadata:
  name: kpi-service
  namespace: vs-blue
  labels: { app: kpi-service, color: blue }
spec:
  type: ClusterIP
  selector: { app: kpi-service, color: blue }
  ports:
    - { name: http, port: 8080, targetPort: 8080, protocol: TCP }
---
apiVersion: v1
kind: Service
metadata:
  name: kpi-service
  namespace: vs-green
  labels: { app: kpi-service, color: green }
spec:
  type: ClusterIP
  selector: { app: kpi-service, color: green }
  ports:
    - { name: http, port: 8080, targetPort: 8080, protocol: TCP }
