apiVersion: v1
kind: Service
metadata:
  name: telegram-service
  namespace: vs-blue
  labels: { app: telegram-service, color: blue }
spec:
  type: ClusterIP
  selector: { app: telegram-service, color: blue }
  ports:
    - { name: http, port: 8081, targetPort: 8081, protocol: TCP }
---
apiVersion: v1
kind: Service
metadata:
  name: telegram-service
  namespace: vs-green
  labels: { app: telegram-service, color: green }
spec:
  type: ClusterIP
  selector: { app: telegram-service, color: green }
  ports:
    - { name: http, port: 8081, targetPort: 8081, protocol: TCP }
